language: perl
sudo: false
perl:
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
before_install:
  - cpanm -n git://github.com/kan/coveralls-perl.git
script: perl Build.PL && ./Build build && cover -test -report coveralls
