version: '2'
services:
    perl:
        image: ghcr.io/kan/docker-perl-cpm/perl-cpm:5.30.1
        volumes:
            - ./:/app
            - perl-local:/app/local
        tty: true
volumes:
  perl-local:
    driver: local
